from django.db import models
from django.db.models import permalink
from django.contrib.auth.models import User

from django.core.files.storage import FileSystemStorage

from sorl.thumbnail.fields import ImageWithThumbnailsField

#
# Coop Users
#
# We extend the standard Django user class because it's easier for now.
#

class CoopUser(models.Model):
    user = models.OneToOneField(User)
    contact_methods = models.OneToOneField('ContactMethods')

#
# Customizable Questions
#
# Each Question:
#  * allows 0 or more FixedAnswers detailing a multiple choice selection
#  * allows an optional free text response
#  * require exactly 1 answer, any number of answers, or a particular minimum/maximum pair

class QuestionCategory(models.Model):
    label = models.CharField(max_length=50)
    parent = models.ForeignKey('QuestionCategory', null=True)

class Question(models.Model):
    category = models.ForeignKey(QuestionCategory)
    question = models.CharField(max_length=100)
    help_text = models.TextField(blank=True)
    min_answers = models.PositiveSmallIntegerField()
    max_answers = models.PositiveSmallIntegerField(null=True)
    free_text_answer_ok = models.BooleanField()
    created_by = models.ForeignKey(CoopUser, related_name="questions_created")
    updated_by = models.ForeignKey(CoopUser, related_name="questions_updated")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class FixedAnswer(models.Model):
    question = models.ForeignKey(Question, related_name="fixed_answers")
    rank = models.PositiveSmallIntegerField()
    answer = models.TextField()
    class Meta:
        unique_together = (('question', 'rank'),)

class AnswerSet(models.Model):
    question = models.ForeignKey(Question, related_name="answer_sets")
    fixed_answers = models.ManyToManyField(FixedAnswer)
    free_text_answer = models.TextField(blank=True)
    created_by = models.ForeignKey(CoopUser)
    created_at = models.DateTimeField(auto_now_add=True)

#
# ContactMethods
# This allows
#

class ContactMethods(models.Model): pass

class Label(models.Model):
    label = models.CharField(max_length=15)
    rank = models.PositiveSmallIntegerField()
    class Meta:
        abstract = True
    def __unicode__(self):
        return self.label

class EmailLabel(Label): pass

class PhoneNumberLabel(Label): pass

class ContactMethod(models.Model):
    contact_methods = models.ForeignKey(ContactMethods)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        abstract = True

class Email(ContactMethod):
    label = models.ForeignKey(EmailLabel)
    email = models.EmailField()
    def __unicode__(self):
        return u"%s: %s" % [self.label, self.email]

class PhoneNumber(ContactMethod):
    label = models.ForeignKey(PhoneNumberLabel)
    phone_number = models.CharField(max_length=20)
    def __unicode__(self):
        return u"%s: %s" % [self.label, self.phone_number]


#
# Versioned Coops
#
# For simplicity, all data associated with a coop (e.g., name, address) can be
# stored in AnswerSet.
#
# When somebody starts editing an existing Coop, we duplicate the existing Coop
# entry, copy all the existing values to it, set most_recent to the already existing id,
# and then save it.  A list of all coops is generated by doing a search for null.
# (ote, some databases may be slow (sequential) for searching on null.  In that
# situation we can specify a hardcoded ID to function as "NULL".)
#
# XXX TODO: We need to specify some way of ordering and organizing
# the answer sets.  As of now, it's just an unordered set.

class Coop(models.Model):
    most_recent = models.ForeignKey('Coop', null=True)
    answer_sets = models.ManyToManyField(AnswerSet)
    contact_methods = models.OneToOneField(ContactMethods)
    created_by = models.ForeignKey(CoopUser, related_name="coops_created")
    created_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return ('show_coop', [str(self.id)])
    get_absolute_url = permalink(get_absolute_url)

    # name = models.CharField(max_length = 50)
    # street_address_1 = models.CharField(max_length = 50, blank = True)
    # street_address_2 = models.CharField(max_length = 50, blank = True)
    # city = models.CharField(max_length = 50, blank = True)
    # state = models.USStateField(blank = True)
    # zip_code = models.CharField(max_length = 10, blank = True)
    # phone = models.CharField(max_length = 13, blank = True)
    # public_email = models.EmailField(blank = True)
    # 
    # number_of_residents = models.IntegerField(blank = True, null = True)
    # average_rent = models.CharField(max_length = 50, blank = True)
    # description = models.TextField(blank = True,
    #         help_text = 'Tell us about your coop, and what makes it special.')
    # founded = models.IntegerField(blank = True, null = True,
    #         help_text = 'When was your coop started?')
    # def __unicode__(self):
    #     return self.name

class CoopPicture(models.Model):
    most_recent = models.OneToOneField(Coop)
    picture = ImageWithThumbnailsField(blank = True, null = True,
            upload_to = "uploads/coop_pictures/%Y/%m/", 
            thumbnail = {'size': (100, 100)},
            extra_thumbnails = {
                'large': {'size': (400, 400)},
            })
